name = "DistMesh"
uuid = "f7ee28b6-bfbf-11e9-3e31-8961b86f052c"
version = "0.2.0"
authors = ["Steve Kelly <kd2cca@gmail.com> and Per-Olof Persson <persson@berkeley.edu"]

[deps]
Delaunator = "466f8f70-d5e3-4806-ac0b-a54b75a91218"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TetGen = "c5d3f3f7-f850-59f6-8a2e-ffc6dc1317ea"

[compat]
Delaunator = "0.1"
GeometryBasics = "0.4"
LinearAlgebra = "1"
StaticArrays = "1.9"
TetGen = "1"
julia = "1.10"

[extras]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TetGen = "c5d3f3f7-f850-59f6-8a2e-ffc6dc1317ea"

[targets]
test = ["Test", "GeometryBasics", "TetGen"]
