name = "DistMesh"
uuid = "f7ee28b6-bfbf-11e9-3e31-8961b86f052c"
authors = ["Steve Kelly <kd2cca@gmail.com>"]
version = "0.1.0"

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TetGen = "c5d3f3f7-f850-59f6-8a2e-ffc6dc1317ea"

[compat]
julia = ">=1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
