name = "DistMesh"
uuid = "f7ee28b6-bfbf-11e9-3e31-8961b86f052c"
license = "MIT"
version = "0.2.0"
authors = ["Per-Olof Persson <persson@berkeley.edu>"]

[deps]
Delaunator = "466f8f70-d5e3-4806-ac0b-a54b75a91218"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
DistMeshCairoMakieExt = "CairoMakie"
DistMeshGLMakieExt = ["GLMakie", "GeometryBasics"]
DistMeshPlotsExt = "Plots"

[compat]
CairoMakie = "0.15"
Delaunator = "0.1"
GLMakie = "0.11, 0.12, 0.13"
GeometryBasics = "0.5"
LinearAlgebra = "1"
Plots = "1"
StaticArrays = "1.9"
julia = "1.10"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CairoMakie"]
